server:
#  port: 8085
  servlet:
    context-path: /pay

spring:
  datasource:
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/education_user?serverTimezone=UTC
    course:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/education_course?serverTimezone=UTC